language: node_js

node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git clone --branch gh-pages https://${GH_REF} dist

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --force --quiet "https://${GitHub_TOKEN}@${GH_REF}" gh-pages:gh-pages
# E: Build LifeCycle

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/dave-wind/VPC.git
